services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ekaant  # Replace with your actual password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - monitoring

  ekaant-app:
    build: ./
    ports:
      - "3009:3009"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:ekaant@psql:5432/postgres
    networks:
      - monitoring
    depends_on:
      - psql
    command: sh -c "npx prisma migrate deploy && npm run start"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3011:3000"
    volumes:
      - grafana_data:/var/lib/grafana 
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_data:
  grafana_data:

networks:
  monitoring: