version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testing  # Replace with your actual username
      POSTGRES_PASSWORD: ekaant  # Replace with your actual password
      POSTGRES_DB: notonProduction  # Replace with your actual database name
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  backend:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://testing:ekaant@db:5432/notonProduction  # Replace with your actual connection string
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && npm start"

volumes:
  postgres_data: