services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ekaant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring
    depends_on:
      - psql

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3011:3000"
    volumes:
      - grafana_data:/var/lib/grafana 
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
  prometheus_data: 

networks:
  monitoring:
